version: '3.8'

services:
  app:
    container_name: nexus-erp-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    env_file:
      - .env
    restart: unless-stopped
