version: '3.8'

services:
  backend:
    container_name: nexus-erp-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - nexus-network

networks:
  nexus-network:
    name: nexus-network
