version: '3.8'

services:
  backend:
    container_name: nexus-erp-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - nexus-network
  redis:
    image: redis:7-alpine
    container_name: nexus-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    networks:
      - nexus-network

networks:
  nexus-network:
    name: nexus-network
